### PR TITLE
add google analytics + fix ts compilation

### PR DESCRIPTION
**Pull request by alee**
I don't think our CI is catching ts errors properly - `yarn build` generates a ton of complaints regarding pino if you run it manually

### CODE REVIEW

**Comment by sgfost** [comment]
Building/type checking the server code doesn't seem to give me any errors or warnings on both 8a41e92 and 097eb0c. No clues whats happening there.. Is it preventing the build for you?

The client build problem looks like the same thing I ran into in #917 which seemed to get fixed by deleting the lockfile and node_modules and reinstalling but its probably bad news if the same thing is happening again

**Comment by sgfost** [comment]
I'm guessing snyk is failing because its expecting to use yarn but I don't have access to it @alee

**Comment by alee** [comment]
> I'm guessing snyk is failing because its expecting to use yarn but I don't have access to it @alee

Just saw that - I think we can ignore this Snyk - I'll configure it to use a slightly better shared organizational account and send you an invite to that (i.e., not tied to my account :sweat_smile:)

You're right about the TS errors disappearing on a clean rebuild which is just plain weird. I think it might be something non-deterministic related to our usage of docker volume mounts and node_modules and maybe a half-baked typescript upgrade that I was running locally. That said the errors I was seeing didn't seem *wrong* per se, mostly things like missing arguments to pino, or being oddly finicky about the type of an interpolated value in the log format string (i.e., %d on a string or something like that). I'll see if I can figure out how to reproduce it...

**Comment by sgfost** [comment]
That is odd. I wonder how the parsing/type checking of format string args is even being done, didn't see anything glancing at pino's type definitions

**Comment by alee** [comment]
one thing I'm not sure about is the `logger.exception(e as Error)` - I think anything can get thrown in JS so probably need to tighten up some of those invocations

https://medium.com/with-orus/the-5-commandments-of-clean-error-handling-in-typescript-93a9cbdf1af5

**Comment by sgfost** [comment]
Yeah maybe unlikely to be an issue but should be easy to add

May be worth a look through some of the stricter `@typescript-eslint` rules (`no-throw-literal` rule made me think of this). Enabling all of them with https://typescript-eslint.io/linting/configs/#strict-type-checked seems like way too much type gymnastics though

**Pull request merged**
