### PR TITLE
feat: tutorial tooltip pulses

### LINKED ISSUE #426: tutorial: emphasize tooltips more
tooltips should have a distinct border

### PR DESCRIPTION
**Pull request by Nick42791**
pulses unless user hovers over it

could be changed to just a few pulses if it were annoying...

should close #426

### CODE REVIEW

**Comment by Nick42791** [comment]
@chrstngyn 
I changed the pulsing to be on the active element
I also made it so that the previous button is that light green color, but I kept the next button orange. I think it gives a nice contrast, but let me know what you think!

Also, @lfaivre, feel free to checkout these changes as well and let me know your thoughts.

Thanks!

**Comment by chrstngyn** [comment]
i like this implementation better now that the blinking is on the active element and that it stops

making the previous button the same color as the border on the active element and step seems confusing. it almost makes me not notice the next button because my focus wants to be drawn to the previous button because of the color association

**Comment by Nick42791** [comment]
> making the previous button the same color as the border on the active element and step seems confusing. it almost makes me not notice the next button because my focus wants to be drawn to the previous button because of the color association

hmm, ok. I was hoping to do the opposite by having the 'next' be bright orange lol. 
do you think that both buttons should be blue?

**Comment by chrstngyn** [comment]
yea, i would try making both blue and see if it looks more cohesive! we could probably get opinions from the play test too.

**Pull request merged**
