### PR TITLE
Build: replace webpack/vue-cli with vite

### LINKED ISSUE #890: try to replace webpack with vite
for speed reasons. HMR is also broken currently

https://github.com/vitejs/vite-plugin-vue2

### PR DESCRIPTION
**Pull request by sgfost**
- upgrade to vue 2.7
- remove vue-cli/webpack stuff and replace with vite + vite-plugin-vue2
- jest setup on the client is replaced with vitest

- [x] resolves #890

### CODE REVIEW

**Comment by sgfost** [comment]
good opportunity to revist code splitting but everything seems to be working now

**Review by alee — COMMENTED** [review]
this worked perfectly on my mac (with hot reloading etc) but on my linux box it brought up these errors

```
 ❯ doc logs -f client                                                                                                                                                                                                       [13:37:00] 
port-of-mars-client-1  | yarn run v1.22.19                                                                                                                                                                                             
port-of-mars-client-1  | $ vite                                                                                                                                                                                                        
port-of-mars-client-1  | /bin/sh: 1: vite: not found                                                                                                                                                                                   
port-of-mars-client-1  | error Command failed with exit code 127.                                                                                                                                                                      
port-of-mars-client-1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.                                                                                                                          
port-of-mars-client-1  | yarn run v1.22.19                                                                                                                                                                                             
port-of-mars-client-1  | $ vite                                                                                                                                                                                                        
port-of-mars-client-1  | /bin/sh: 1: vite: not found                                                                                                                                                                                   
port-of-mars-client-1  | error Command failed with exit code 127.                                                                                                                                                                      
port-of-mars-client-1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.                                                                                                                          
port-of-mars-client-1  | yarn run v1.22.19                                                                                                                                                                                             
port-of-mars-client-1  | $ vite       
...
```

might be something I have to clean up on my local filesystem? I removed an old (2022) `client/node_modules` directory and also tried running on a completely fresh checkout also but with the same results

**Comment by sgfost** [comment]
docker cache maybe?

**Comment by alee** [comment]
seems like it, running `docker system prune -a` and rebuilding fixed the issue on linux. maybe there's a volume with cached node_modules that's not getting cleaned out properly on rebuild?

I'll try to look into it when I get a chance but if anyone else figures it out first please go for it

**Comment by sgfost** [comment]
`docker compose build --no-cache` works as well, not sure how to make it invalidate the layer cache otherwise, but probably a non-issue at this point

**Pull request merged**
